version: '3'

services:
  go-api:
    build:
      context: ./api
    ports:
      - "8080:8080"
      
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: golang
      MYSQL_USER: goteam
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"